import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './auth/AuthProvider'
import './globals.css'
import NavigationBar from './components/NavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme='winter'>
      <body className={inter.className}>
        <AuthProvider>
          <NavigationBar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
